# 연습문제

### #1번

In [9]:
import numpy as np
np.random.seed(0)
a = np.random.randint(1,7,100)
print(a.sum()/len(a))

3.42


### #2번

In [10]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
print(a+b)

[[ 8 10 12]
 [14 16 18]]


### #3번

In [12]:
a = np.arange(1,10)
a*3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

### #4번

In [14]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### #5번

In [23]:
a = np.arange(49,-1,-1)
print(a)
b = np.arange(0,50)
print(b[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


### #6번

In [52]:
np.full((3,3,3),'',dtype='U10')
#np.zeros([3,3,3],dtype='U10')

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

### #7번

In [53]:
np.full((3,3,3),'playdata',dtype='U8')

array([[['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']]], dtype='<U8')

### #8번

In [73]:
a = np.arange(2,41,2)
a = a.reshape(2,2,5)
a

array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]],

       [[22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40]]])

### #9번

In [75]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### #10번

In [82]:
np.random.seed(0)
a = np.random.randint(0,2,9)
a.astype("?").reshape(3,3)

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [103]:
np.random.seed(0)
a = np.random.rand(10)*10
a.astype('i')

array([5, 7, 6, 5, 4, 6, 4, 8, 9, 3], dtype=int32)

In [161]:
a = np.ones((10,10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### #11번

In [207]:
a = np.ones((10,10))
#a[0] = 0
#a[len(a)-1] = 0
#a[::,0::len(a)-1]=0
a[:,[0,-1]]=0
a[[0,-1],:]=0
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### #12번

In [273]:
a = np.ones((8,8))

a[1::2,::2]=0
a[::2,1::2]=0
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


### #13번

In [289]:
a = np.array([[1,0],[0,1]])
a = np.tile(a,(4,4))
a
# np.tile(np.array([[1,0],[0,1]]),(4,4))
# np.tile(np.eye(2),(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [292]:
a = np.arange(1,5)
print(a)
even = np.array([True if i%2 == 0 else False for i in range(1,5)])
print(even)

[1 2 3 4]
[False  True False  True]


### #14번

In [315]:
a = np.arange(0,11)
for i in range(10):
    if a[i]>3 and a[i]<7:
        a[i] = a[i]*-1
print(a)

[ 0  1  2  3 -4 -5 -6  7  8  9 10]


In [331]:
a = np.arange(11)
even = np.array([a[i]*-1 if a[i]>3 & 3<a[i]<7 else a[i] for i in range(11)])
print(even)

[ 0  1  2  3 -4 -5 -6  7  8  9 10]


### #15번

In [338]:
sum_num = 0
a = np.arange(1,101)
for i in range(len(a)):
    if a[i]%3 == 0:
        sum_num += a[i]
print(sum_num)

#np.arange(3,101,3).sum()

1683


### #16번

In [346]:
a = np.linspace(0.1,0.9,9)
a

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### #17번

In [9]:
import numpy as np
while True:
    try:
        a = int(input("숫자를 입력하세요 : "))
        print(a)
        for _ in range(a):
            c = np.array([np.random.choice(45,6,replace=False)])
            c.sort()
            print(c)
        break;
    except:
        print("자연수만 입력해주세요.")

숫자를 입력하세요 :  3


3
[[ 4  5 14 28 36 43]]
[[ 8 29 32 35 37 38]]
[[ 0  5  8 18 21 26]]


### #18번

In [24]:
cunt = 0
resp_time = np. array([158,  85, 205,  24,  42, 175, 188, 149, 153, 171, 137,  55, 108,
                       199, 177, 209, 218,  76, 103, 189, 110, 192, 136, 119,   4, 102,
                       177, 212, 110,  37, 163,  32,  77,  22, 125, 184,  46, 139,  72,
                       168, 133, 209, 148,  47, 102,  65, 160,  56,  11,  96, 169, 118,
                        55, 135, 217,  49, 100,  85, 179,  15, 139, 199, 124, 142,  15,
                        49, 168, 171, 168, 177, 147,  23, 199,  26,  51,  42,  90, 128,
                       186, 169, 129,  70, 198, 111,  81, 150,  17, 177, 201,  10,  75,
                       199,  55, 151, 183, 152, 119, 193, 110, 204])
for i in range(len(resp_time)):
    if resp_time[i]>200 :
        cunt += 1
print(cunt)

#(resp_time>200).sum()
#len(resp_time[resp_time>200])

8


In [36]:
a = np.percentile(resp_time,25)
print(a)
b = np.percentile(resp_time,50)
print(b)
c = np.percentile(resp_time,75)
print(c)
d = np.percentile(resp_time,100)
print(d)

e = sorted(resp_time)
print(e)

71.5
131.0
175.5
218.0
[4, 10, 11, 15, 15, 17, 22, 23, 24, 26, 32, 37, 42, 42, 46, 47, 49, 49, 51, 55, 55, 55, 56, 65, 70, 72, 75, 76, 77, 81, 85, 85, 90, 96, 100, 102, 102, 103, 108, 110, 110, 110, 111, 118, 119, 119, 124, 125, 128, 129, 133, 135, 136, 137, 139, 139, 142, 147, 148, 149, 150, 151, 152, 153, 158, 160, 163, 168, 168, 168, 169, 169, 171, 171, 175, 177, 177, 177, 177, 179, 183, 184, 186, 188, 189, 192, 193, 198, 199, 199, 199, 199, 201, 204, 205, 209, 209, 212, 217, 218]


### #19번

In [93]:
p = ["뽀로로", "루피", "크롱"]
result = np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
                   1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
                   1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
                   2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
                   2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
                   2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
                   1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
                   2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
                   0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
                   0, 1])
a = np.bincount(result)
ki = ''
dic = dict(zip(p, a)) 

for key,value in dic.items():
    if value == max(dic.values()):
        ki = key
        
print(f"{ki}가 {max(dic.values())} 표로 학생회장으로 선출되었습니다.")

#count = np.bincount(result,minlength=3)
#winner_index = count.argmax()
#print(f"{p[winner_index]}가 {count[winner_index]} 표로 학생회장으로 선출되었습니다.")

[81 53 66]
뽀로로가 81 표로 학생회장으로 선출되었습니다.


### #20번

### #21번

### #22번

### #23번

### #24번

### #25번