In [17]:
import numpy as np

ar = np.array([_ for _ in range(10)])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#(10,) -> 1차원의 10칸 갖는 array
ar.shape

(10,)

In [26]:
x = np.array([1,2,3])
x.dtype

dtype('int32')

In [27]:
x = np.array([1.0,2.0,3.0])
x.dtype

dtype('float64')

In [28]:
x = np.array([1,2,3.0])
x.dtype

dtype('float64')

In [32]:
x = np.array([1,2,3], dtype = 'f')
x.dtype

dtype('float32')

In [36]:
x = np.array([1,2,3], dtype = 'U')
x.dtype
x

array(['1', '2', '3'], dtype='<U1')

In [35]:
x[0]+x[1]

'12'

In [37]:
np.array([0,1,-1,0])/np.array([1,0,0,0])

C:\Users\user\AppData\Local\Temp\ipykernel_20076\1727448928.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1,-1,0])/np.array([1,0,0,0])
C:\Users\user\AppData\Local\Temp\ipykernel_20076\1727448928.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1,-1,0])/np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

In [38]:
data = [0,1,2,3,4,5,6,7,8,9]
answer = [2 * d for d in data]
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [40]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
2*x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
list_samp = [_ for _ in range(3)]
print(list_samp * 5)

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]


In [44]:
a = np.array([1,2,3])
b = np.array([10,20,30])

2 * a + b

array([12, 24, 36])

In [45]:
a == 2

array([False,  True, False])

In [46]:
b > 10 

array([False,  True,  True])

In [48]:
(a==2) & (b>10)

array([False,  True, False])

In [50]:
c = np.array([[0,1,2],[3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [51]:
len(c)

2

In [52]:
len(c[0])

3

In [54]:
c.shape

(2, 3)

In [59]:
a = np.array([[10,20,30,40],[50,60,70,80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [60]:
ab = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16],
              [17,18,19,20]])
ab

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [61]:
print(a.ndim) #차원이 몇 차원인지 알 수 있게해주는 함수
print(a.shape)

2
(2, 4)


In [69]:
a[0,0]

10

In [70]:
a[0,1]

20

In [71]:
a[-1,-1]

80

In [72]:
a[0,:]

array([10, 20, 30, 40])

In [73]:
a[:,1]

array([20, 60])

In [79]:
test = [[1,2,3,4],[5,6,7,8]]
print(test[1][1])

6


In [80]:
a[0][0]

10

In [81]:
a[1,1]

60

In [88]:
a=[[1,2,3,4],[5,6,7,8]]
print(a[0][:3])

[1, 2, 3]


In [92]:
m = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]])
#1
print(m[1][1])
#2
print(m[2][4])
#3
print(m[1,1:3])
#4
print(m[1:,2])
#5
print(m[:2,3:])

6
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


In [102]:
a = np.zeros(5) #타입을 정해주지않으면 기본으로 float형으로 생성됨.
a
c = np.zeros((5,2), dtype = 'i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [100]:
d = np.zeros(5,dtype="U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [101]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE" #u4로 잡아줬기때문에 4글자 이상이면 잘려서 입력됨.
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [98]:
e = np.ones((2,3,4),dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [107]:
b = np.zeros((2,3))
b
f = np.ones_like(b,dtype="f")
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [108]:
g = np.empty((4,3))
g

array([[1.00973333e-311, 2.42092166e-322, 0.00000000e+000],
       [0.00000000e+000, 1.78020168e-306, 5.64233733e-067],
       [4.71752445e-090, 1.33621728e+165, 6.58993924e-043],
       [1.46415462e-075, 6.99196247e+228, 2.22522596e-306]])

In [109]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
np.arange(3,21,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [111]:
ex = np.linspace(0,100,5)
ex

array([  0.,  25.,  50.,  75., 100.])

In [112]:
ex2 = np.logspace(0,100,5)
ex2

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

In [113]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [115]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [117]:
b = a.reshape(3,4)
b 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [119]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [120]:
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [121]:
a.reshape(2,-1,2).flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [122]:
a.reshape(2,-1,2).ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [125]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [126]:
x.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [127]:
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [128]:
x[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [131]:
a1 = np.ones((2,3))
a2 = np.zeros((2,2))
np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [133]:
b1 = np.ones((2,3))
b2 = np.zeros((3,3))
np.vstack([b1,b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [134]:
c1 = np.ones((3,4))
c2 = np.zeros((3,4))
np.dstack([c1,c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [135]:
c = np.stack([c1,c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [136]:
c.shape

(2, 3, 4)

In [137]:
c = np.stack([c1,c2],axis = 1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [138]:
c = np.stack([c1,c2],axis = 2)
c

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [140]:
np.r_[np.array([1,2,3]),np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [143]:
np.c_[np.array([1,2,3]),np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [145]:
a = np.array([[0,1,2],[3,4,5]])
np.tile(a,2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [146]:
np.tile(a,(3,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [175]:
q = np.zeros([3,3])
w = np.ones([3,2])
qw= np.hstack([q,w])
e = np.arange(10,151,10).reshape(3,5)
qwe = np.vstack([qw,e])
np.tile(qwe,(2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [176]:
x = np.arange(1,10001)
y = np.arange(10001,20001)

In [177]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

Wall time: 2.99 ms


In [178]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [182]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
c = np.array([1,2,3,4])
#a==b

a>=b

array([False,  True,  True,  True])

In [183]:
np.all(a==b)

False

In [184]:
np.all(a==c)

True

In [185]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [186]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [187]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [188]:
100*x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [190]:
a = np.array([1.0,2.0,3.0])
b = np.array([2.0,2.0,2.0])
a*b

array([2., 4., 6.])

In [191]:
x = np.array([1,2,3,4])
np.sum(x)

10

In [192]:
x.sum()

10

In [196]:
x = np.arange(12).reshape(3,-1)

In [198]:
x.sum(axis=0)

array([12, 15, 18, 21])

In [199]:
x.sum(axis=1)

array([ 6, 22, 38])

In [201]:
x = np.arange(20).reshape(2,5,-1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [202]:
x.min()

0

np.min(4)

In [203]:
np.min(x)

0

In [ ]:
x.min(axis=0)

In [204]:
np.min(x,axis=1)

array([[ 0,  1],
       [10, 11]])

In [205]:
x.min(axis=2)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [210]:
x = np.arange(20).reshape(2,5,-1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [211]:
x.argmin()

0

In [212]:
np.argmin(x)

0

In [213]:
x.argmin(axis=0)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [214]:
np.argmin(x,axis=1)

array([[0, 0],
       [0, 0]], dtype=int64)

In [215]:
x.argmin(axis=2)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [217]:
x = np.arange(20).reshape(2,5,-1)

In [218]:
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [219]:
x.max()

19

In [220]:
x.max(axis=0)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [221]:
np.max(x,axis=1)

array([[ 8,  9],
       [18, 19]])

In [222]:
x.max(axis=2)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [223]:
x = np.arange(20).reshape(2,5,-1)

In [224]:
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [225]:
x.argmax()

19

In [227]:
np.argmax(x)

19

In [228]:
x.argmax(axis=0)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

In [231]:
np.argmax(x,axis=1)

array([[4, 4],
       [4, 4]], dtype=int64)

In [233]:
x.argmax(axis=2)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [234]:
x=np.array([1,2,3,1])
x.mean()

1.75

In [235]:
np.median(x)

1.5

In [236]:
np.all([True,True,False])

False

In [243]:
np.any([True,True,False])

True

In [238]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                                [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                                [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                                [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                                [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

In [251]:
#1
print(practice.max())
#2
print(practice.sum(axis=0))
#3
print(practice.max(axis=0))
#4
print(practice.mean(axis=1))
#5
print(practice.min(axis=1))

9.0
[20.1 27.  23.6 26.  28.2 26.5]
[8.2 8.8 8.  9.  7.7 8.9]
[5.33333333 5.11666667 5.71666667 4.11666667 4.95      ]
[1.1 2.7 0.7 0.2 2.7]


In [252]:
a = np.array([42,38,12,25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [253]:
a[j]

array([12, 25, 38, 42])

In [255]:
a = np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,1,0]])

[1 4 5]


In [264]:
print(a[:,[0,1,0]])

[[1 2 1]
 [3 4 3]
 [5 6 5]]


In [ ]:
scores = np.array([[1,2,3,4],
                   [46,99,100,71],
                   [81,59,90,100]])


In [273]:
j = np.argsort(scores[1,:])
print(scores[:,j])


[[  1   4   2   3]
 [ 46  71  99 100]
 [ 81 100  59  90]]


In [285]:
np.random.seed(0)

In [286]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [287]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [288]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [289]:
x = np.arange(10)

In [290]:
np.random.shuffle(x)
x

array([3, 6, 4, 5, 2, 9, 7, 8, 1, 0])

In [311]:
np.random.seed(0)
a = np.random.randint(0,2,size=100)
count=0
for i in a:
    if i == 1:
        count += 1
print(count/100)

0.56


In [313]:
np.random.seed(0)
b = np.random.randint(1,7,size=100)
#print(b.sum()/100)
b.mean()

3.42

In [314]:
np.unique([11,11,2,2,34,34])

array([ 2, 11, 34])

In [315]:
a = np.array(['a','b','b','c','a'])
index, count = np.unique(a,return_counts=True)

In [316]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [317]:
count

array([2, 2, 1], dtype=int64)

In [319]:
np.bincount(([1,1,2,2,2,3]), minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)